# Generated by Django 5.1.1 on 2024-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
