# Generated by Django 5.1.1 on 2024-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Статус платежа"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(verbose_name="Сумма платежа"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата платежа"),
        ),
    ]
