# Generated by Django 5.1.1 on 2024-09-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_status_alter_payment_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="user",
            new_name="owner",
        ),
    ]
